# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\reposBCICompetition\bcihack2\Desarrollo\PythonScripts\scripts\GUIModule\registro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(981, 558)
        Dialog.setMouseTracking(True)
        Dialog.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.label_accion = QtWidgets.QLabel(Dialog)
        self.label_accion.setGeometry(QtCore.QRect(81, 202, 16, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_accion.setFont(font)
        self.label_accion.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_accion.setText("")
        self.label_accion.setAlignment(QtCore.Qt.AlignCenter)
        self.label_accion.setObjectName("label_accion")
        self.label_orden = QtWidgets.QLabel(Dialog)
        self.label_orden.setGeometry(QtCore.QRect(30, 200, 931, 81))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.label_orden.setFont(font)
        self.label_orden.setStyleSheet("color: rgb(25, 50, 200);")
        self.label_orden.setAlignment(QtCore.Qt.AlignCenter)
        self.label_orden.setObjectName("label_orden")
        self.cruz = QtWidgets.QLabel(Dialog)
        self.cruz.setEnabled(True)
        self.cruz.setGeometry(QtCore.QRect(450, 270, 70, 70))
        self.cruz.setMouseTracking(False)
        self.cruz.setText("")
        self.cruz.setPixmap(QtGui.QPixmap("d:\\reposBCICompetition\\bcihack2\\Desarrollo\\PythonScripts\\scripts\\GUIModule\\cross.png"))
        self.cruz.setObjectName("cruz")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(150, 430, 651, 81))
        self.progressBar.setStyleSheet("color: rgb(255, 0, 0);")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "IndicatorApp"))
        self.label_orden.setText(_translate("Dialog", "Comenzando..."))
